navikt/pensjonssimulator

pom.xml, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/AlderspensjonResult.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/acl/AlderspensjonResultMapperV4.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/acl/AlderspensjonResultV4.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/acl/AlderspensjonSpecMapperV4.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/acl/AlderspensjonSpecV4.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/client/pen/acl/PenAlderspensjonResult.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/client/pen/acl/PenAlderspensjonResultMapper.kt, src/main/kotlin/no/nav/pensjon/simulator/tech/doc/OpenApiConfiguration.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/api/acl/AlderspensjonSpecMapperV4Test.kt
Tilpasning til seneste versjon av [Simulerings-APIer - alternativ 3 - Request/Response](https://confluence.adeo.no/pages/viewpage.action?pageId=583317319)  > Simuler Alderspensjon.
NB: [Denne PEN PR](https://github.com/navikt/pesys/pull/13095) må deployes først.
=> PEK-490 Adjust 'simuler alderspensjon V4' response

src/main/kotlin/no/nav/pensjon/simulator/core/SimulatorContext.kt, src/main/kotlin/no/nav/pensjon/simulator/core/SimulatorCore.kt, src/main/kotlin/no/nav/pensjon/simulator/core/beregn/Alderspensjon2011SisteBeregningCreator.kt, src/main/kotlin/no/nav/pensjon/simulator/core/beregn/Alderspensjon2016SisteBeregningCreator.kt, src/main/kotlin/no/nav/pensjon/simulator/core/beregn/Alderspensjon2025SisteBeregningCreator.kt, src/main/kotlin/no/nav/pensjon/simulator/core/beregn/SisteBeregningCreator.kt, src/main/kotlin/no/nav/pensjon/simulator/core/beregn/SisteBeregningCreatorBase.kt, src/main/kotlin/no/nav/pensjon/simulator/core/person/PersongrunnlagMapper.kt, src/main/kotlin/no/nav/pensjon/simulator/generelt/GenerelleData.kt, src/main/kotlin/no/nav/pensjon/simulator/generelt/GenerelleDataHolder.kt, src/main/kotlin/no/nav/pensjon/simulator/generelt/GenerelleDataSpec.kt, src/main/kotlin/no/nav/pensjon/simulator/generelt/Person.kt, src/main/kotlin/no/nav/pensjon/simulator/generelt/client/pen/PenGenerelleDataClient.kt, src/main/kotlin/no/nav/pensjon/simulator/generelt/client/pen/acl/PenGenerelleDataResult.kt, src/main/kotlin/no/nav/pensjon/simulator/generelt/client/pen/acl/PenGenerelleDataResultMapper.kt, src/main/kotlin/no/nav/pensjon/simulator/krav/KravService.kt, src/main/kotlin/no/nav/pensjon/simulator/krav/client/KravClient.kt, src/main/kotlin/no/nav/pensjon/simulator/krav/client/pen/PenKravClient.kt, src/main/kotlin/no/nav/pensjon/simulator/krav/client/pen/acl/PenKravSpec.kt, src/test/kotlin/no/nav/pensjon/simulator/generelt/client/pen/acl/PenGenerelleDataResultMapperTest.kt, src/test/kotlin/no/nav/pensjon/simulator/krav/client/pen/PenKravClientTest.kt, src/test/kotlin/no/nav/pensjon/simulator/testutil/TestDateUtil.kt
Del 1 av endringer for å støtte "innlogget" simulering.
Henter kravhode og statsborgerskap fra PEN der det behøves.
Pluss fjernet ubrukt kode i `SimulatorContext`.
=> PEK-551 Use kravhode, statsborgerskap

src/main/kotlin/no/nav/pensjon/simulator/tech/security/ApiAuthenticationManagerResolver.kt, src/main/kotlin/no/nav/pensjon/simulator/tech/security/SecurityConfiguration.kt, src/main/kotlin/no/nav/pensjon/simulator/tech/security/ingress/TokenAudienceValidator.kt, src/main/resources/application.properties, src/test/kotlin/no/nav/pensjon/simulator/tech/security/ApiAuthenticationManagerResolverTest.kt, src/test/kotlin/no/nav/pensjon/simulator/tech/security/ingress/TokenAudienceValidatorTest.kt, src/test/kotlin/no/nav/pensjon/simulator/tech/security/ingress/TokenScopeValidatorTest.kt
Simulatoren skal støtte kall med client credentials-token (Entra ID) fra PEN og kalkulator-backend for simulering.
Dette kommer i tillegg til eksisterende støtte for kall med maskinporten-token fra TPO-er.
Kallene fra PEN er for å støtte simulering V1, V2 og V3 (gamle tjenester for TPO-er). Disse kallene vil ha path `/api/tpo/**`.
Kallene fra kalkulator-backend er for simulering for personer logget inn på Nav. Disse kallene vil ha path `/api/nav/**`.
=> PEK-555 Add support for client credentials tokens

.nais/api/apiendpoints.yaml, .nais/deploy-dev.yml, pom.xml, src/main/kotlin/no/nav/pensjon/simulator/tech/doc/OpenApiConfiguration.kt
Aksio bruker [Maskinporten-delegering](https://docs.digdir.no/docs/Maskinporten/maskinporten_func_delegering).
For å støtte dette brukes `delegationSource`, noe som krever at scope bruker "/" som separator.
Et eget scope for Aksio er dermed opprettet.
Skrur også av `debug`, da vi ikke har hatt bruk for dette.
Tilhørende PR for API-dok: [Oppdatering etter at simulering2025 støtter delegering](https://github.com/navikt/pensjon-ekstern-api/pull/19)
=> Add separate scope for Aksio

.nais/deploy-dev.yml, src/main/kotlin/no/nav/pensjon/simulator/beholdning/BeholdningerMedGrunnlagResult.kt, src/main/kotlin/no/nav/pensjon/simulator/beholdning/BeholdningerMedGrunnlagService.kt, src/main/kotlin/no/nav/pensjon/simulator/beholdning/BeholdningerMedGrunnlagSpec.kt, src/main/kotlin/no/nav/pensjon/simulator/beholdning/FolketrygdBeholdningService.kt, src/main/kotlin/no/nav/pensjon/simulator/beholdning/client/BeholdningClient.kt, src/main/kotlin/no/nav/pensjon/simulator/beholdning/client/pen/PenBeholdningClient.kt, src/main/kotlin/no/nav/pensjon/simulator/beholdning/client/pen/acl/PenBeholdningerMedGrunnlagSpec.kt, src/main/kotlin/no/nav/pensjon/simulator/beholdning/client/pen/acl/PenBeholdningerMedGrunnlagSpecMapper.kt, src/main/kotlin/no/nav/pensjon/simulator/core/afp/offentlig/pre2025/Pre2025OffentligAfpPersongrunnlag.kt, src/main/kotlin/no/nav/pensjon/simulator/core/endring/EndringPersongrunnlag.kt, src/main/kotlin/no/nav/pensjon/simulator/core/krav/KravhodeCreator.kt, src/main/kotlin/no/nav/pensjon/simulator/core/person/eps/EpsService.kt, src/main/kotlin/no/nav/pensjon/simulator/person/PersonService.kt, src/main/kotlin/no/nav/pensjon/simulator/tech/time/DateUtil.kt
Skrur på mer funksjonalitet i `KravhodeCreator` for simulering (henter beholding, kravhode, uføredata fra PEN).
La til `EndringPersongrunnlag` for simulering av 'endring av AP'.
Trakk ut EPS-funksjoner i en egen klasse: `EpsService`.
=> PEK-551 Henter beholdning etc

src/main/kotlin/no/nav/pensjon/simulator/core/afp/offentlig/pre2025/Pre2025OffentligAfpPersongrunnlag.kt, src/main/kotlin/no/nav/pensjon/simulator/core/afp/offentlig/pre2025/Pre2025OffentligAfpUttakGrad.kt, src/main/kotlin/no/nav/pensjon/simulator/core/afp/offentlig/pre2025/Pre2025OffentligAfpUttaksgrad.kt, src/main/kotlin/no/nav/pensjon/simulator/core/endring/EndringPersongrunnlag.kt, src/main/kotlin/no/nav/pensjon/simulator/core/endring/EndringUttakGrad.kt, src/main/kotlin/no/nav/pensjon/simulator/core/krav/KravhodeCreator.kt, src/main/kotlin/no/nav/pensjon/simulator/core/person/PersongrunnlagService.kt, src/main/kotlin/no/nav/pensjon/simulator/core/person/eps/EpsService.kt
Skrur på gjenværende funksjonalitet for simulering (opprettelse av uttaksgrader og persongrunnlag).
La til `EndringUttakGrad` for simulering av 'endring av AP'.
La til `Pre2025OffentligAfpUttakGrad` for simulering av gammel ("pre-2025") offentlig AFP.
Trakk ut persongrunnlag-funksjoner i en egen klasse: `PersongrunnlagService`.
=> PEK-551 Complete support for 'personlig simulering'

src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/tpo/viapen/acl/v3/TpoSimuleringResultV3.kt, src/test/kotlin/no/nav/pensjon/simulator/sak/client/pen/PenSakClientTest.kt
Endring 1: Angir tidssone i tester som inkluderer datoer med tid 00:00:00, da disse ellers vil feile når testene kjøres på GitHub i Finland (tiden blir da 23:00:00 dagen før).
Endring 2: Angir JSON-format på datoer i V3-responsen.
=> JSON-format dates, specify timezone in unit test

src/main/kotlin/no/nav/pensjon/simulator/tech/sporing/Sporing.kt, src/main/kotlin/no/nav/pensjon/simulator/tech/sporing/SporingsloggService.kt, src/main/kotlin/no/nav/pensjon/simulator/tech/sporing/client/samhandling/acl/SamhandlingSporing.kt, src/main/kotlin/no/nav/pensjon/simulator/tech/sporing/client/samhandling/acl/SamhandlingSporingMapper.kt, src/main/kotlin/no/nav/pensjon/simulator/tech/sporing/web/SporingInterceptor.kt
Forvalteren av sporingsloggen etterlyste bruk av feltet `dataForespoersel` (ref. [springslogg-dok](https://sikkerhet.nav.no/docs/sikker-utvikling/sporingslogg)).
Endringen gjør at mottatt forespørsel fra TPO logges i `dataForespoersel` og returnerte data logges i `leverteData`.
=> PEK-831 Use dataForespoersel in sporingslogg

src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/AlderspensjonService.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/AlderspensjonSpecMapper.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/tpo/direct/TpoAlderspensjonController.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/tpo/direct/acl/v4/AlderspensjonSpecMapperV4.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/spec/AlderspensjonSpec.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/AlderspensjonServiceTest.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/AlderspensjonSpecMapperTest.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/api/tpo/direct/acl/v4/AlderspensjonResultMapperV4Test.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/api/tpo/direct/acl/v4/AlderspensjonSpecMapperV4Test.kt
Gjelder tjenesten 'simuler alderspensjon V4'.
Sjekker om bruker har gjeldende vedtak. I så fall brukes simuleringstype `ENDR_ALDER` eller `ENDR_AP_M_AFP_OFFENTLIG_LIVSVARIG`.
Sjekker også om bruker har gjenlevenderettighet. I så fall kan ikke simulering gjennomføres. Dette er samme oppførsel som i V3-tjenesten i PEN ([SimulerAlderspensjonProviderV3](https://github.com/navikt/pensjon-pen/blob/6c4619c1ebe861d7d0bea68e6289e6f6e3b7ad63/pen-app/src/main/java/no/nav/pensjon/pen_app/provider/ws/simuleralderspensjon/v3/support/SimulerAlderspensjonProviderV3.kt#L65)).
=> PEK-1019 Support 'endring' in 'TPO AP V4' service

.github/workflows/deploy-alerts.yml, .github/workflows/deploy.yaml, .nais/alerts-q1.yml, .nais/deploy-q1.yml
SPK tester tjenesten 'simuler alderspensjon V3' i Q1.
Dersom V3 skal simuleres av pensjonssimulator ("flyttet kode") istedenfor PEN, må det opprettes et Q1-miljø for pensjonssimulator.
Denne PR oppretter et slikt Q1-miljø.
Relaterte PR:
- PEN: [PR 15160](https://github.com/navikt/pensjon-pen/pull/15160)
- TP: [PR 731](https://github.com/navikt/tp/pull/731)
Relatert [commit i pensjon-selvbetjening-fss-gateway](https://github.com/navikt/pensjon-selvbetjening-fss-gateway/commit/ee3ba57f52c9e14243891761afccaaef95b20019)
NB 1: Når "flyttet kode" er påskrudd for V3, så vil SPK fortsatt kalle V3 via PEN (som sender kallet videre til pensjonssimulator). Dermed behøves ingress-tilgang i Q1 kun for PEN (`pensjon-pen-q1`). 
NB 2: De nye tjenestene (simuler AP V4, folketrygdbeholdning, TMU) gjør kall …
=> PEK-1029 Deploy to Q1

src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/viapen/NavViaPenAlderspensjonController.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/viapen/acl/v2/result/NavBeregningResultV2.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/viapen/acl/v2/result/NavSimuleringResultMapperV2.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/viapen/acl/v2/result/NavSimuleringResultV2.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/viapen/acl/v2/result/NavYtelseKomponentV2.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/viapen/acl/v2/spec/NavSimuleringSpecMapperV2.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/viapen/acl/v2/spec/NavSimuleringSpecV2.kt, src/main/kotlin/no/nav/pensjon/simulator/core/SimulatorCore.kt, src/main/kotlin/no/nav/pensjon/simulator/core/afp/offentlig/pre2025/Pre2025OffentligAfpPersongrunnlag.kt, src/main/kotlin/no/nav/pensjon/simulator/core/beholdning/BeholdningUpdaterUtil.kt, src/main/kotlin/no/nav/pensjon/simulator/core/domain/regler/grunnlag/PersonDetalj.kt, src/main/kotlin/no/nav/pensjon/simulator/core/endring/EndringPersongrunnlag.kt, src/main/kotlin/no/nav/pensjon/simulator/core/krav/KravhodeCreator.kt, src/main/kotlin/no/nav/pensjon/simulator/core/person/PersongrunnlagMapper.kt, src/main/kotlin/no/nav/pensjon/simulator/core/result/SimulatorOutput.kt, src/main/kotlin/no/nav/pensjon/simulator/core/spec/SimuleringSpec.kt, src/main/kotlin/no/nav/pensjon/simulator/krav/client/pen/acl/PenKravhodeMapper.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/viapen/acl/v2/spec/NavSimuleringSpecMapperV2Test.kt, src/test/kotlin/no/nav/pensjon/simulator/krav/client/pen/acl/PenKravhodeMapperTest.kt
Diverse rettelser for 'gammel' (pre-2025) offentlig AFP:
- "inntekt under gradert uttak" brukes for inntekt under AFP-perioden
- årsverdien (`ar`) i `Merknad` for `Poengtall` settes til poengtallets årsverdi
- verdien `heltUttakDato` i `SimuleringSpec` modifiseres i simuleringen; den modifiserte verdien returneres i responsen
- opprydding i håndtering av `virkFom`/`virkTom` vs `rolleFomDato`/`rolleTomDato` i `PersonDetalj`
=> PEK-556 For AFP_ETTERF_ALDER use inntektUnderGradertUttak as AFP-inntekt

src/main/kotlin/no/nav/pensjon/simulator/core/afp/offentlig/livsvarig/LivsvarigOffentligAfpUtil.kt, src/main/kotlin/no/nav/pensjon/simulator/core/beholdning/BeholdningUpdater.kt, src/main/kotlin/no/nav/pensjon/simulator/core/beholdning/BeholdningUpdaterUtil.kt, src/main/kotlin/no/nav/pensjon/simulator/core/beregn/AlderspensjonVilkaarsproeverOgBeregner.kt, src/main/kotlin/no/nav/pensjon/simulator/core/domain/regler/beregning2011/AfpOffentligLivsvarigGrunnlag.kt, src/main/kotlin/no/nav/pensjon/simulator/core/domain/regler/grunnlag/Garantipensjonsbeholdning.kt, src/main/kotlin/no/nav/pensjon/simulator/core/domain/regler/grunnlag/Persongrunnlag.kt, src/main/kotlin/no/nav/pensjon/simulator/core/domain/regler/krav/Kravhode.kt, src/main/kotlin/no/nav/pensjon/simulator/core/domain/reglerextend/beregning2011/Beregning2011Extension.kt, src/main/kotlin/no/nav/pensjon/simulator/core/domain/reglerextend/grunnlag/GrunnlagExtension.kt, src/main/kotlin/no/nav/pensjon/simulator/core/krav/KravhodeCreator.kt, src/main/kotlin/no/nav/pensjon/simulator/core/virkning/FoersteVirkningDatoRepopulator.kt, src/main/kotlin/no/nav/pensjon/simulator/krav/client/pen/acl/PenKravhodeMapper.kt, src/main/kotlin/no/nav/pensjon/simulator/krav/client/pen/acl/PenPersongrunnlag.kt, src/main/kotlin/no/nav/pensjon/simulator/tech/time/Periode.kt, src/test/kotlin/no/nav/pensjon/simulator/core/afp/offentlig/livsvarig/LivsvarigOffentligAfpUtilTest.kt, src/test/kotlin/no/nav/pensjon/simulator/core/beholdning/BeholdningUpdaterUtilTest.kt, src/test/kotlin/no/nav/pensjon/simulator/tech/time/PeriodeTest.kt
Inkluderer innvilget livsvarig offentlig AFP i persongrunnlaget for løpende ytelser som hentes fra PEN.
Endrer også `onsketVirkningsdato` til å være `LocalDate` i `Kravhode`.
Tilhørende endring i PEN: [PR 15710](https://github.com/navikt/pensjon-pen/pull/15710)
=> Include 'innvilget livsvarig offentlig AFP' in persongrunnlag

src/main/kotlin/no/nav/pensjon/simulator/generelt/organisasjon/Organisasjonsnummer.kt, src/main/kotlin/no/nav/pensjon/simulator/person/Pid.kt, src/test/kotlin/no/nav/pensjon/simulator/generelt/organisasjon/OrganisasjonsnummerTest.kt
Bruker 'inline value class' for å redusere 'runtime overhead', ref. [Inline value classes](https://kotlinlang.org/docs/inline-classes.html).
Pluss validering av lengde på organisasjonsnummer.
=> Use inline value class for PID and organisasjonsnummer

src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/SimuleringFacade.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/SimulertPensjonEllerAlternativ.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/UfoereAlternativSimuleringService.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/direct/acl/v3/result/NavSimuleringResultMapperV3.kt
Håndtering av tilfellet der ingen alternative uttak finnes for uføre. Siden første uttaksalder ikke kan økes, kan ikke helt uttak ved normalder være et alternativ, slik det er normalt (for ikke-uføre).
=> Handle 'no result' case for uføre

src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/AlderspensjonService.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/AlternativSimuleringService.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/AlternativtUttakFinder.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/AlternativtUttakService.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/SimuleringFacade.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/UfoereAlternativSimuleringService.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/UfoereAlternativtUttakFinder.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/UfoereAlternativtUttakService.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/convert/SimulatorOutputConverter.kt, src/main/kotlin/no/nav/pensjon/simulator/beholdning/FolketrygdBeholdningService.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/AlternativtUttakServiceTest.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/UfoereAlternativSimuleringServiceTest.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/convert/SimulatorOutputConverterTest.kt, src/test/kotlin/no/nav/pensjon/simulator/beholdning/FolketrygdBeholdningServiceTest.kt
Ved å angi tid (dagens dato) som parameter gjør man enhetstestene tidsuavhengige (man kan angi en konstant verdi for "dagens dato").
Bruker også en mer spesifikk parameter enn `simuleringSpec`, siden kun én verdi i spec-en brukes: `inntektUnderGradertUttakBeloep`. Parameteren får navnet `inntektVedFase1Uttak`, som er mer korrekt, siden den angir inntekt ved uttak av AFP, ikke ved gradert uttak.
=> Inject time into SimulatorOutputConverter

src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/direct/acl/v3/spec/NavSimuleringSpecMapperV3.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/direct/acl/v3/spec/NavSimuleringSpecMapperV3Test.kt
Endring i simuleringstjenesten for 'ny' kalkulator:
Bruk EPS' inntekt/pensjon fra vedtak (istedenfor å 'overskrive' vedtaksverdiene med brukeroppgitte verdier).
=> PEK-1290 Bruk EPS' inntekt/pensjon fra vedtak

end-to-end-test/src/main/resources/afp-etterfulgt-av-alder-response.json, src/main/kotlin/no/nav/pensjon/simulator/afp_etterfulgt_ap/api/tpo/acl/v0/result/AfpEtterfulgtAvAlderspensjonResultMapperV0.kt, src/main/kotlin/no/nav/pensjon/simulator/afp_etterfulgt_ap/api/tpo/acl/v0/result/AfpEtterfulgtAvAlderspensjonResultV0.kt, src/main/kotlin/no/nav/pensjon/simulator/afp_etterfulgt_ap/api/tpo/acl/v0/spec/AfpEtterfulgtAvAlderspensjonSpecMapperV0.kt, src/main/kotlin/no/nav/pensjon/simulator/core/SimulatorCore.kt, src/main/kotlin/no/nav/pensjon/simulator/core/result/PensjonPeriode.kt, src/main/kotlin/no/nav/pensjon/simulator/core/result/RegisterData.kt, src/main/kotlin/no/nav/pensjon/simulator/core/result/SimulatorOutput.kt, src/main/kotlin/no/nav/pensjon/simulator/core/result/SimulertAlderspensjon.kt, src/main/kotlin/no/nav/pensjon/simulator/core/spec/SimuleringSpec.kt, src/main/kotlin/no/nav/pensjon/simulator/core/spec/SimuleringSpecUtil.kt, src/main/kotlin/no/nav/pensjon/simulator/inntekt/InntektService.kt, src/test/kotlin/no/nav/pensjon/simulator/afp_etterfulgt_ap/api/tpo/acl/v0/result/AfpEtterfulgtAvAlderspensjonResultMapperV0Test.kt, src/test/kotlin/no/nav/pensjon/simulator/afp_etterfulgt_ap/api/tpo/acl/v0/spec/AfpEtterfulgtAvAlderspensjonSpecMapperV0Test.kt, src/test/kotlin/no/nav/pensjon/simulator/core/result/PensjonPeriodeTest.kt, src/test/kotlin/no/nav/pensjon/simulator/core/result/SimulertAlderspensjonTest.kt, src/test/kotlin/no/nav/pensjon/simulator/inntekt/InntektServiceTest.kt
Oppdatering av API i.h.t. [dokumentasjon for v0.95](https://confluence.adeo.no/spaces/PEN/pages/679381624/API+-+AFP+etterfulgt+av+AP):
Lagt til:
- `sisteLignetInntektBrukt`
- `sisteLignetInntektAar`
- `garantipensjonsbeholdningForUttak`
Fjernet:
- `fremtidigAarligInntektTilAfpUttak`
- `garantipensjonssats`
- `saertilleggsats`
- `delingstall`
- `forholdstall`
Endret:
- `pensjonsbeholdningFoerUttak` -> `pensjonsbeholdningForUttak`
- Flyttet noe logikk fra `AfpEtterfulgtAvAlderspensjonResultMapperV0` til domeneklassene `PensjonPeriode` og `SimulertAlderspensjon`
- Delt opp lange funksjoner i mindre funksjoner
- Fjernet `+ 1` i nevneren i testen for `afpGrad` (for å matche formelen brukt)
=> PEK-1297 Version 0.95 of API 'AFP etterfulgt av AP'

src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/SimulertPensjon.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/direct/acl/v3/result/NavSimuleringResultMapperV3.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/direct/acl/v3/result/NavSimuleringResultV3.kt, src/main/kotlin/no/nav/pensjon/simulator/alderspensjon/convert/SimulatorOutputConverter.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/alternativ/AlternativtUttakServiceTest.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/direct/acl/v3/result/NavSimuleringResultMapperV3Test.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/api/nav/direct/acl/v3/result/NavSimuleringResultMapperV3Test2.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/api/tpo/direct/TpoAlderspensjonResultMapperTest.kt, src/test/kotlin/no/nav/pensjon/simulator/alderspensjon/convert/SimulatorOutputConverterTest.kt
Dette er en foreløpig løsning for å unngå 0 trygdetid for kapittel 19-tilfeller.
NB: Flagget `harNokTrygdetidForGarantipensjon` vil være `true` også hvis kapittel 19-trygdetid er minst 5 år (selv om 'garantipensjon' er et kapittel 20-begrep). Navnet på flagget kan vi endre på senere.
=> Use trygdetid = max of kapittel 19 and kapittel 20

pom.xml
Midlertidig fix.
For ordentlig fix, så foreslår Google:
> The long-term solution involves configuring libraries that use agents to load them as proper Java agents at application startup using the -javaagent flag. This requires understanding how the specific library or framework handles agent configuration. For example, Mockito can be configured to use its agent explicitly.
=> Temp. fix for "Java agent has been loaded dynamically" warning

.docker/Dockerfile, .docker/Dockerfile-EndToEndTest
> I Nav betaler vi for Chainguard images som er minimale images med ekstra sikkerhetstiltak. Her får du distroless images med (nesten alltid) null sårbarheter.
– [Nav Security Playbook: Valg av baseimage](https://sikkerhet.nav.no/docs/sikker-utvikling/baseimages/)
=> TPP-18 Use Chainguard Docker image
